const fs = require('fs');
const path = require('path');
const mammoth = require('mammoth');
import express from "express";
import cors from "cors";
import morgan from "morgan";
import dotenv from "dotenv";
import collectRoutes from "./routes";
import { Router } from "express";
import speechRoutes from "./routes/speech";
import quizRoutes from "./routes/quiz";
import { Router } from "express";
import fetch from "node-fetch";
import { getSecret } from "../utils/secrets";
import { Router } from "express";
import { readFileSync } from "fs";
import path from "path";
import evaluateController from "../services/evaluate";
import { saveSession } from "../services/store";
import OpenAI from "openai";
import { getSecret } from "../utils/secrets";
import { CosmosClient } from "@azure/cosmos";
import { BlobServiceClient } from "@azure/storage-blob";
import { getSecret } from "../utils/secrets";
import { DefaultAzureCredential } from "@azure/identity";
import { SecretClient } from "@azure/keyvault-secrets";
import React from "react";
import { createRoot } from "react-dom/client";
import App from "./ui/App";
import React, { useEffect, useState, useRef } from "react";
import axios from "axios";
import * as SpeechSDK from "microsoft-cognitiveservices-speech-sdk";

